## Tarea 2: (Usando notebook de jupyter)** 

### Karen Violeta García Hernández


- Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
> 	- Expected Output:\\
> 	- Original List: [12.23, 13.32, 100, 36.32]\\
> 	- One-dimensional numpy array: [ 12.23 13.32 100. 36.32] 

In [12]:
import numpy as np

def npArray(list):
    a = np.array(list)
    return a

originalList = [12.23, 13.23, 100, 36.32]
numpyArray = npArray(originalList)
print(numpyArray)

[ 12.23  13.23 100.    36.32]



 - Write a Python program to create a null vector of size 10 and update sixth value to 11.


In [5]:
nullVector = np.zeros(10)
nullVector[5] = 11
print(nullVector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]



- Write a Python program to create a array with values ranging from 12 to 38.


In [8]:
arrayRang = np.random.randint(12,38,10)
print(arrayRang)

[25 20 36 27 36 25 33 37 25 18]



- Write a Python program to reverse an array (first element becomes last).
 

In [13]:
def reverseArray(array):
    rev = np.flipud(array)
    return rev

numpyArray = reverseArray(numpyArray)
print(numpyArray)

[ 36.32 100.    13.23  12.23]



- Write a Python program to create a 2d array with 1 on the border and 0 inside.
>     Expected Output:
> 	- Original array:
> $$
     \begin{pmatrix}
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.\\
     1. &1.& 1.& 1.& 1.
     \end{pmatrix}
     $$
> 	1 on the border and 0 inside in the array
     $$
     \begin{pmatrix}
     1. &1.& 1.& 1.& 1.\\
     1. &0& 0& 0& 1.\\
     1. &0& 0& 0& 1.\\
     1. &0& 0& 0& 1.\\
     1. &1.& 1.& 1.& 1.
     \end{pmatrix}
     $$
> 


In [15]:
arrayOnes = np.ones((5,5))
arrayOnes[1:-1,1:-1] = 0
print(arrayOnes)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]



 - Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern
> 
> 	- Checkerboard pattern:
>$$
     \begin{pmatrix} 
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
        0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
        1 & 0 & 1 & 0 & 1 & 0 & 1 & 0
     \end{pmatrix}
     $$
> 	- **Hint** Explore the use of $x[a::b,::c] = d,	x[::e,f::g] = h$, where the letters are integer numbers.


In [27]:
numpyArray = np.zeros((8,8))
numpyArray[1::2,::2] = 1
numpyArray[::2,1::2] = 1
print(numpyArray)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


 - Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.
>     - Sample Array [0, 12, 45.21 ,34, 99.91]  
>     - Expected Output:
>     - Values in Fahrenheit degrees: [0.0 12.0 45.21 34.0 99.91]
>     - Values in Centigrade degrees: [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778].
> 	- *Use functions and list comprehension* read the link https://www.pythonforbeginners.com/lists/list-comprehensions-in-python/, to additional information about of list comprehension in python.
>     


In [32]:
List = [0, 12, 45.21, 34, 99.91]
print(List)

#Fahrenheit = list(map(lambda x: 1.8*x + 32, List))

C = map(lambda x: (float(5)/9)*(x-32), List)
print([i for i in C])


[0, 12, 45.21, 34, 99.91]
[-17.77777777777778, -11.11111111111111, 7.3388888888888895, 1.1111111111111112, 37.727777777777774]


 - Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
> 	- Expected Output:
> 	- Array1: [ 0 10 20 40 60 80]
> 	- Array2: [10, 30, 40, 50, 70, 90]
> 	- Set difference between two arrays: [ 0 20 60 80] 
> 	- **Hint**: explore the use of function *np.setdiff1d*.


In [28]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
diference = np.setdiff1d(array1, array2)
print(diference)

[ 0 20 60 80]


 - Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

In [22]:
arrayDiag = np.diagflat([4, 5, 6, 8])
print(arrayDiag)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
